---
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
# Define the trigger. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
"on":
  workflow_call:
    # Neede secrets to be given. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets
    secrets:
      SSH_HOST:
        description: SSH server to log in via SSH
        required: true
      SSH_USERNAME:
        description: SSH username to log in via SSH
        required: true
      SSH_KEY:
        description: SSH secret key to log in via SSH
        required: true
      ENVIRONMENT:
        description: Environment file string to be used during deployment
        required: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:
  deploy:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment
    environment:
      name: production
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsname
      - name: Checkout repository
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        # https://github.com/actions/checkout/
        uses: actions/checkout@v3
      - name: Run deployment script on host server
        # https://github.com/appleboy/ssh-action
        uses: appleboy/ssh-action@v1.0.0
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv
        env:
          # Repository name to deploy
          REPO_NAME: ${{ github.repository }}
          # Repository url to deploy
          REPO_URL: https://github.com/${{ github.repository }}
          # Git revison to deploy
          REVISON: ${{ github.ref }}
          # Enviroment file string to be used with docker-compose files
          # https://hexdocs.pm/dotenvy/dotenv-file-format.html
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key:  ${{ secrets.SSH_KEY }}
          envs: REPO_NAME,REPO_URL,REVISON,ENVIRONMENT
          # Get deploy script from github
          # Make script executable if not. https://wiki.ubuntuusers.de/chmod/
          # Run script
          script: |
            curl -s https://raw.githubusercontent.com/Good-Games-Munich/reusable-workflows/main/deploy.bash > /tmp/deploy.bash
            chmod +x deploy.bash
            bash /tmp/deploy.bash